const foods=[['Lẩu Thái','thai','medium','fun','🍲','Một nồi lẩu nóng hổi cực hợp nhóm bạn.'],['Gà rán','fastfood','low','fun','🍗','Nhanh, ngon, dễ ăn.'],['Bún đậu mắm tôm','vietnamese','low','fun','🥢','Món quốc dân cho buổi tụ tập.'],['Phở bò','vietnamese','low','chill','🍜','Một tô phở nóng cho buổi gặp mặt nhẹ nhàng.'],['Cơm tấm','vietnamese','low','any','🍚','Đơn giản nhưng luôn ngon.'],['Thịt nướng Hàn Quốc','korean','high','fun','🥩','BBQ cùng hội bạn cực hợp.'],['Tokbokki','korean','medium','fun','🌶️','Cay cay, vui vui.'],['Sushi','japanese','high','chill','🍣','Nhẹ nhàng và tinh tế.'],['Ramen','japanese','medium','chill','🍜','Ramen nóng cho buổi tối chill.'],['Pad Thai','thai','medium','chill','🍝','Mì Thái đậm vị.'],['Pizza','fastfood','medium','fun','🍕','Chia pizza cùng nhóm bạn.'],['Burger','fastfood','low','fun','🍔','Một chiếc burger cho ngày không muốn nghĩ.']].map(x=>({name:x[0],type:x[1],price:x[2],mood:x[3],emoji:x[4],desc:x[5]}));
const games=[['Truth or Dare',2,10,'😈','fun','Một người chọn Truth hoặc Dare.'],['20 Questions',2,6,'❓','chill','Đặt câu hỏi để đoán từ khóa.'],['Đoán bài hát',2,12,'🎵','fun','Nghe một đoạn nhạc và đoán tên bài.'],['Pictionary',3,8,'🎨','fun','Một người vẽ, người khác đoán.'],['Quiz nhóm',3,20,'🧠','competitive','Chia đội và thi xem ai hiểu biết hơn.'],['Ma Sói',5,15,'🐺','competitive','Suy luận và tìm ra Ma Sói.'],['Mafia',6,20,'🕵️','competitive','Đấu trí giữa Mafia và dân thường.'],['Charades',4,15,'🎭','fun','Diễn tả mà không được nói.'],['Ai hiểu nhóm nhất?',4,15,'👀','fun','Xem ai hiểu hội bạn nhất.'],['Team Battle',9,30,'🔥','competitive','Chia đội và thi nhiều thử thách.'],['Đấu hát',5,20,'🎤','fun','Chia đội và thi xem ai hát sung hơn.']].map(x=>({name:x[0],min:x[1],max:x[2],emoji:x[3],mood:x[4],desc:x[5]}));
const songs=[['Nàng Thơ','Hoàng Dũng','pop','chill'],['Bước Qua Mùa Cô Đơn','Vũ.','ballad','chill'],['Em Của Ngày Hôm Qua','Sơn Tùng M-TP','pop','fun'],['See Tình','Hoàng Thùy Linh','pop','fun'],['3107','W/n','ballad','chill'],['Tình Đơn Phương','Lam Trường','bolero','chill'],['Dynamite','BTS','kpop','fun'],['How You Like That','BLACKPINK','kpop','fun'],['APT.','ROSÉ & Bruno Mars','usuk','fun'],['Perfect','Ed Sheeran','usuk','chill'],['Believer','Imagine Dragons','rock','competitive'],['Faded','Alan Walker','remix','chill'],['Rap God','Eminem','rap','competitive']].map(x=>({title:x[0],artist:x[1],genre:x[2],mood:x[3]}));
let playerCount=4;const pick=a=>a[Math.floor(Math.random()*a.length)];const mood=()=>document.getElementById('mood').value;function sync(){playerCount=Math.max(2,Math.min(30,+document.getElementById('players').value||4));document.getElementById('players').value=playerCount;document.getElementById('gp').textContent=playerCount}document.getElementById('players').addEventListener('change',sync);
function randomFood(){let b=document.getElementById('budget').value,t=document.getElementById('foodType').value,m=mood();let a=foods.filter(x=>(b==='any'||x.price===b)&&(t==='any'||x.type===t)&&(m==='any'||x.mood===m||x.mood==='any'));if(!a.length)a=foods;let x=pick(a);render('foodCard',`${x.emoji}<h3>${x.name}</h3><p>${x.desc}</p>`);document.getElementById('rf').textContent=x.emoji+' '+x.name;document.getElementById('rfd').textContent=x.desc;toast('🍜 Đã chọn món ăn!')}
function randomGame(){sync();let m=mood(),a=games.filter(x=>playerCount>=x.min&&playerCount<=x.max&&(m==='any'||x.mood===m||x.mood==='fun'));if(!a.length)a=games.filter(x=>playerCount>=x.min&&playerCount<=x.max);if(!a.length)a=games;let x=pick(a);render('gameCard',`${x.emoji}<h3>${x.name}</h3><p>${x.desc}</p><button onclick="randomGame()">🎲 RANDOM GAME KHÁC</button>`);document.getElementById('rg').textContent=x.emoji+' '+x.name;document.getElementById('rgd').textContent=x.desc;toast('🎮 Đã chọn game!')}
function randomSong(){let g=document.getElementById('genre').value,m=mood(),a=songs.filter(x=>(g==='any'||x.genre===g)&&(m==='any'||x.mood===m||x.mood==='fun'));if(!a.length)a=songs.filter(x=>g==='any'||x.genre===g);if(!a.length)a=songs;let x=pick(a);render('songCard',`🎤<h3>${x.title}</h3><p>${x.artist}</p><small>${x.genre.toUpperCase()}</small>`);document.getElementById('rs').textContent='🎵 '+x.title;document.getElementById('rsa').textContent=x.artist;toast('🎤 Đã chọn bài hát!')}
function randomAll(){document.getElementById('result').classList.remove('hide');randomFood();setTimeout(randomGame,250);setTimeout(randomSong,500);setTimeout(()=>document.getElementById('result').scrollIntoView({behavior:'smooth'}),700);toast('🍊 Đã tạo kèo hoàn chỉnh!')}
function render(id,html){let e=document.getElementById(id);e.classList.remove('pop');void e.offsetWidth;e.classList.add('pop');e.innerHTML=html}function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1800)}
